import "./globals.css";
import { Inria_Sans } from 'next/font/google'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inriaSans = Inria_Sans({ subsets: ['latin'], weight: ['400', '700']})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inriaSans.className}>{children}</body>
    </html>
  );
}
